apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-client
  labels:
    app: k8s-client
spec:
  replicas: 2
  selector:
    matchLabels:
      app: k8s-client
  template:
    metadata:
      labels:
        app: k8s-client
    spec:
      containers:
        - name: k8s-client
          image: arifpirxada/k8s-client:1.0.0
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: k8s-client-service
spec:
  selector:
    app: k8s-client
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
