apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
stringData:
  DATABASE_URL: <mongodb://username:password@mongodb:27017/dbname?authSource=admin>
  MONGO_USER: <username>
  MONGO_PASSWORD: <password>
  DATABASE_NAME: <dbname>